name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install pytest flake8 bandit

      - name: Run lint
        run: |
          flake8 . --ignore=E402

      - name: Run tests
        run: |
          pytest

      - name: Run security scan
        run: |
          bandit -r . -x tests
